### ISSUE TITLE
Question about large casbin rules.

### ISSUE THREAD

**Issue by pigochu** [php-casbin/yii-permission#6]
I cut the db query from  yii2 debug .

![image](https://user-images.githubusercontent.com/1013744/93041428-1b72a880-f67f-11ea-8023-03ea7ccef368.png)

Yii-permission  will query all data from casbin_rule every request.
If I have 50000 users , 10 domains ,  and set every user to some domain.
The  query results will be very very large .
How to optimze it ?

**Comment by hsluoyz** [comment]
You should only load all policy data at initial time. Enforce with the policy data in memory for each request.

**Comment by pigochu** [comment]
> You should only load all policy data at initial time. Enforce with the policy data in memory for each request.
I did not use swoole . How data save in memory ?
If I have many users and domain , It also uses a lot of memory right ?

**Comment by hsluoyz** [comment]
@techoner @yk17310320725

**Comment by techoner** [comment]
@pigochu `yii-permission` does not implement `FilteredAdapter`

**Comment by hsluoyz** [comment]
@yk17310320725 

similar issue to: https://github.com/php-casbin/php-casbin/issues/56
